---
 out_dir: '../results/run_14/'
 dataset_dir: "../chembl-data/chembl_28/chembl_28_sqlite/chembl28-cleaned.smi" 
 which_vocab: "regex" # "selfies" or "regex"
 vocab_path: "./vocab/chembl_regex_vocab.yaml"
 percentage: 1

 rnn_config:
  # embedding
  num_embeddings: 75 # size of vocab + <eos> + <sos> + <pad>
  embedding_dim: 512

  # rnn
  input_size: 512 # size of the recurrent neural network
  hidden_size: 1024
  num_layers: 3
  dropout: 0.2

 batch_size: 512
 shuffle: True
 num_epoch: 200
 which_optimizer: adam
 learning_rate: 0.01
 weight_decay: 0.001