---
 out_dir: '../results/run_25/'
 dataset_dir: "../chembl-data/chembl_28/chembl_28_sqlite/chembl28-cleaned.smi" 
 which_vocab: "regex" # "selfies", "regex", or "char"
 vocab_path: "./vocab/chembl_regex_vocab.yaml"
 percentage: 1

 rnn_config:
  # embedding
  num_embeddings: 75 # size of vocab + <eos> + <sos> + <pad>. char: 47, regex:75
  embedding_dim: 512
  rnn_type: "GRU" # LSTM or GRU

  # rnn
  input_size: 512 # size of the recurrent neural network
  hidden_size: 1024
  num_layers: 3
  dropout: 0

 batch_size: 256
 shuffle: True
 num_epoch: 50
 which_optimizer: sgd
 learning_rate: 0.05
 weight_decay: 0.0005